[project]
name = "paper-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Takumi Yamada", email = "110591229+takumi-ya@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
paper-ai = "paper_ai:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
